# 访问错误消息

在**处理异常**时，依然可以如下所示地**访问**其错误消息：

```
try:
    # some code
except ZeroDivisionError as e:
   # some code
   print("ZeroDivisionError occurred: {}".format(e))
```

应该会输出如下所示的结果：

```
ZeroDivisionError occurred: division by zero
```

因此依然可以访问错误消息，即使已经处理异常以防止程序崩溃！

如果没有要处理的具体错误，依然可以如下所示地访问消息：

```
try:
    # some code
except Exception as e:
   # some code
   print("Exception occurred: {}".format(e))
```

`Exception` 是所有**内置异常的基础类**。你可以在[此处](https://docs.python.org/3/library/exceptions.html#bltin-exceptions)详细了解 Python 的异常。

点击进去浏览官方的文档，我已经阅读了部分的错误，这样对于以后调试程序的帮助是很大的；如果出现错误，首先就可能从官方文档中找到原因所在。